"""empty message

Revision ID: fa2c91b653bb
Revises: a3c6fd976de8
Create Date: 2024-10-29 21:11:57.207193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2c91b653bb'
down_revision = 'a3c6fd976de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
